### ISSUE TITLE
Fixing C2 errors

### ISSUE THREAD

**Issue by MrPepka** [speed47/dvdisaster#66]
Is there any technical possibility for this program to also fix C2 errors in sectors? I mean errors caused by the degradation of the medium. I rip a lot of game discs and I care about the highest image quality of the ripped disc
It's also nice if the program detects copy protection that deliberately damages some sectors (SafeDisc, Bitpool, LaserLock, Ring PROTECH etc), thanks to which it would be possible to save copy-protected game discs

**Comment by speed47** [comment]
Unfortunately, there is no way to fix a C2 error, because when you have such errors, it means that all the builtin error-correction of the disc and reader have failed as the amount of read errors is higher that the amount that could be transparently corrected with builtin error correction mechanisms and additional data burned on the CD.

This means that this part of the data is simply lost. This is why dvdisaster exists: it provides additional error-correction data, on top of the already builtin mechanisms, when you burn a CD, so that you can later recover data if C2 errors happen. But if they happen on a disc where dvdisaster additional data doesn't exist, then it's too late: your data is lost.

Copy protection mechanisms and such are completely out of scope of dvdisaster too.

**Comment by MrPepka** [comment]
OK, so how can we explain that the programs used as part of the redump.org project, i.e. DiscImageCreator and redumper, can re-read sectors with C2 errors so that the drive is able to correct them? Why can't dvdisaster also have this feature?

**Comment by speed47** [comment]
I'm working on my spare time on this project for free, and "we" (actually, I) have nothing to "explain" to you. Please adjust your tone, entitled Internet stranger.

Now, because this can also serve as a technical information point for other people asking themselves the same question, here's the explanation you requested. These softwares repeatedly ask the drive to read the C2-errored sectors again so that maybe at some point the drive will read them differently, with less errors, that fall under the threshold of the maximum errors that can be corrected with the builtin error-correction data that the CD has for each sector. This only works if the errors amount for a given sector is slightly above the threshold, and is done is the hope that reading it again and again, as this is a very sensitive process that is error-prone per itself (laser adjustment, vibrations and such), might at one point yield an amount of errors that falls riight below the max thresholds of errors that can be corrected from the builtin ECC in this sector. If your CD is really damaged, this won't work. There's no "magic" there.

I won't add this to dvdisaster because the main page that you didn't read, explains that I'm not the upstream maintainer and my role is mainly to ensure that it is adapted to newer OSes and still work. Not working on new features that go out of scope of the program.

Note that you can still use other programs to dump an ISO of the disc (such as the ones you cited), then load this ISO into dvdisaster and get it correct the errors, if and only if the disc itself was augmented with dvdisaster data beforehand.

**Comment by MrPepka** [comment]
I just asked a question, sorry if I offended anyone. OK, then I close the issue

**Comment by speed47** [comment]
No worries. By the way, you can enable a setting that will make dvdisaster reread several times a faulty sector, which is probably as close as it gets to the "attempt to fix C2 sectors" of the other software.

<img width="367" alt="reread" src="https://github.com/speed47/dvdisaster/assets/218502/636b1db7-b490-4033-855b-80c757bb289c">
