### ISSUE TITLE
RS03 requires a minimum of 15 or 16 roots if --no-bdr-defect-management is specified

### ISSUE THREAD

**Issue by jpovixwm** [speed47/dvdisaster#79]
When calculating the RS03 layout, dvdisaster tries to find the smallest medium size that will result in at least 8 roots. However, even if the `--no-bdr-defect-management` CLI flag is specified, the function `RS03Layout *CalcRS03Layout(Image *image, int target)` still performs its checks using defect-management-enabled medium sizes:
https://github.com/speed47/dvdisaster/blob/45ff2c5fdadd7296691f59a52297cb1e1ab8fa30/src/rs03-common.c#L536-L563
This means that the `NODM` variant of a medium size will only be chosen if the equivalent DM-enabled medium size yields at least 8 roots.
I've tried obtaining the maximum image sizes that will result in a NODM variant being chosen, and came up with this table:

| Medium size       | Max ISO sectors | Roots | Redundancy |
| ----------------- | --------------- | ----- | ---------- |
| BD_SL_SIZE_NODM   | 11408740        | 15    | 6.25%      |
| BD_DL_SIZE_NODM   | 22817482        | 15    | 6.25%      |
| BDXL_TL_SIZE_NODM | 45635950        | 15    | 6.25%      |
| BDXL_QL_SIZE_NODM | 58271740        | 16    | 6.69%      |

However, I'm not sure whether this is a bug or intended behavior, as I know that using a redundancy lower than 20% triggers a warning message anyway, so maybe these redundancies of ~6.25% are too small to be useful anyway?

**Comment by speed47** [comment]
Thanks for your report!

You're right, the above code is incorrect, and yields sub-optimal results when defect management is disabled. This was not intentional.
That said, a redundancy of 6.25% is not really a good idea, but it's still better than nothing, i.e. as you said, sub-20% get a  warning printed, and if the user ignores it, we'll make the assumption that they know what they're doing. If for some reason you have to burn only one BD and you happen to have 6% space remaining, it's still better to fill it up with parity data than not doing anything with it!

**Comment by speed47** [comment]
fixed by #80, thanks for your report (and review!)
