### ISSUE TITLE
Appimage no longer works in Ubuntu 24.04

### ISSUE THREAD

**Issue by rflgrt** [speed47/dvdisaster#90]
Hi,

when I tried to start the Appimage of v0.79.10-pl3 on Ubuntu 24.04 (dvdisaster worked in previous Ubuntu versions) I get the following error message:

`Gtk-Message: Failed to load module "appmenu-gtk-module"
Gtk-Message: Failed to load module "atk-bridge"
/tmp/.mount_dvdisaJunE6x/usr/bin/dvdisaster: symbol lookup error: /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libgail.so: undefined symbol: g_once_init_enter_pointer`

Best wishes

**Comment by speed47** [comment]
Interestingly, a workaround was to delete the libgail-common package from your OS: for some reason AppImage tries to use it and of course it fails as the AppImage libraries are not the same version than your host.

I just rebuild and reuploaded the AppImage version of the latest release to include libgail-common, so that it no longer tries to use the host one, this should work without requiring any workaround.

**Comment by rflgrt** [comment]
Thanks a lot for the fast fix! That solved the problem.
Also many thanks for keeping this useful tool alive!

**Comment by Mo1sture** [comment]
It looks like a version of this issue still exists. I'm unable to correctly use the GUI (checkboxes don't render) on Ubuntu 24.04 or the latest pop os release.

In console:

`Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"

(dvdisaster:12442): Gtk-WARNING **: /lib/x86_64-linux-gnu/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(dvdisaster:12442): Gtk-WARNING **: Loading IM context type 'ibus' failed

(dvdisaster:12442): Gtk-WARNING **: /lib/x86_64-linux-gnu/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(dvdisaster:12442): Gtk-WARNING **: Loading IM context type 'ibus' failed
`
I'd really like to not have to use windows in the last step of authoring my backups. Thank you!
